server:
  # 端口
  port: 8081

spring:
  datasource:
    username: root
    password: jinitaimei
    url: jdbc:mysql://127.0.0.1:3306/sa-token?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8&zeroDateTimeBehavior=CONVERT_TO_NULL
  liquibase:
    change-log: classpath:liquibase/master.xml
    enabled: true
############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false

mybatis-plus:
  type-aliases-package: com.sml.satoken.mapper.entity
  global-config:
    banner: false
    db-config:
      logic-delete-field: deleted
      where-strategy: not_empty
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    #不加这个查询数据为空时，字段将被隐藏
    call-setters-on-nulls: true
    jdbc-type-for-null: null
  mapper-locations: classpath:mapper/*Mapper.xml

logging:
  config: classpath:config/logback-dev.xml