server:
  port: 8999

spring:
  datasource:
    username: root
    password: mysql1sGreat
    url: jdbc:mysql://152.168.170.220:3306/sa-token?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8&zeroDateTimeBehavior=CONVERT_TO_NULL
  liquibase:
    change-log: classpath:liquibase/master.xml
    enabled: false
  redis:
    host: 152.168.170.211
    port: 6379
    password: ido85redis
    database: 31